Name = "Aurora DNS"
Description = ''''''
URL = "https://www.pcextreme.com/dns-health-checks"
Code = "auroradns"
Since = "v0.4.0"

Example = '''
AURORA_API_KEY=xxxxx \
AURORA_SECRET=yyyyyy \
lego --email you@example.com --dns auroradns -d '*.example.com' -d example.com run
'''

[Configuration]
  [Configuration.Credentials]
    AURORA_API_KEY = "API key or username to used"
    AURORA_SECRET = "Secret password to be used"
  [Configuration.Additional]
    AURORA_ENDPOINT = "API endpoint URL"
    AURORA_POLLING_INTERVAL = "Time between DNS propagation check"
    AURORA_PROPAGATION_TIMEOUT = "Maximum waiting time for DNS propagation"
    AURORA_TTL = "The TTL of the TXT record used for the DNS challenge"

[Links]
  API = "https://libcloud.readthedocs.io/en/latest/dns/drivers/auroradns.html#api-docs"
  GoClient = "https://github.com/nrdcg/auroradns"
