Name = "Internet.bs"
Description = ''''''
URL = "https://internetbs.net"
Code = "internetbs"
Since = "v4.5.0"

Example = '''
INTERNET_BS_API_KEY=xxxxxxxxxxxxxxxxxxxxxxxxxx \
INTERNET_BS_PASSWORD=yyyyyyyyyyyyyyyyyyyyyyyyyy \
lego --email you@example.com --dns internetbs -d '*.example.com' -d example.com run
'''

[Configuration]
  [Configuration.Credentials]
    INTERNET_BS_API_KEY = "API key"
    INTERNET_BS_PASSWORD = "API password"
  [Configuration.Additional]
    INTERNET_BS_POLLING_INTERVAL = "Time between DNS propagation check"
    INTERNET_BS_PROPAGATION_TIMEOUT = "Maximum waiting time for DNS propagation"
    INTERNET_BS_TTL = "The TTL of the TXT record used for the DNS challenge"
    INTERNET_BS_HTTP_TIMEOUT = "API request timeout"

[Links]
  API = "https://internetbs.net/internet-bs-api.pdf"
