Name = "Dyn"
Description = ''''''
URL = "https://dyn.com/"
Code = "dyn"
Since = "v0.3.0"

Example = '''
DYN_CUSTOMER_NAME=xxxxxx \
DYN_USER_NAME=yyyyy \
DYN_PASSWORD=zzzz \
lego --email you@example.com --dns dyn -d '*.example.com' -d example.com run
'''

[Configuration]
  [Configuration.Credentials]
    DYN_CUSTOMER_NAME = "Customer name"
    DYN_USER_NAME = "User name"
    DYN_PASSWORD = "Password"
  [Configuration.Additional]
    DYN_POLLING_INTERVAL = "Time between DNS propagation check"
    DYN_PROPAGATION_TIMEOUT = "Maximum waiting time for DNS propagation"
    DYN_TTL = "The TTL of the TXT record used for the DNS challenge"
    DYN_HTTP_TIMEOUT = "API request timeout"

[Links]
  API = "https://help.dyn.com/rest/"
