# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#   name = "github.com/x/y"
#   version = "2.4.0"
#
# [prune]
#   non-go = false
#   go-tests = true
#   unused-packages = true

[prune]
  non-go = true
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/miekg/dns"
  version = "1.1.15"

[[constraint]]
  name = "gopkg.in/square/go-jose.v2"
  version = "2.3.1"

[[constraint]]
  name = "golang.org/x/crypto"
  branch = "master"

[[constraint]]
  name = "golang.org/x/net"
  branch = "master"

[[constraint]]
  name = "golang.org/x/oauth2"
  branch = "master"

[[constraint]]
  name = "google.golang.org/api"
  branch = "master"

[[constraint]]
  name = "github.com/rainycape/memcache"
  branch = "master"

[[constraint]]
  name = "github.com/decker502/dnspod-go"
  version = "0.2.0"

[[constraint]]
  name = "github.com/dnsimple/dnsimple-go"
  version = "0.30.0"

[[constraint]]
  name = "github.com/namedotcom/go"
  branch = "master"

[[constraint]]
  name = "github.com/ovh/go-ovh"
  branch = "master"

[[constraint]]
  name = "github.com/timewasted/linode"
  branch = "master"

[[constraint]]
  name = "github.com/nrdcg/goinwx"
  version = "0.6.0"

[[constraint]]
  name = "github.com/linode/linodego"
  version = "0.10.0"

[[constraint]]
  name = "gopkg.in/ns1/ns1-go.v2"
  branch = "v2"

[[constraint]]
  name = "github.com/sacloud/libsacloud"
  version = "1.25.1"

[[constraint]]
  name = "github.com/transip/gotransip"
  version = "5.14"

[[constraint]]
  name = "github.com/exoscale/egoscale"
  version = "0.18.1"

[[constraint]]
  name = "github.com/akamai/AkamaiOPEN-edgegrid-golang"
  version = "0.7.4"

[[constraint]]
  name = "github.com/oracle/oci-go-sdk"
  version = "5.13.0"

[[constraint]]
  name = "github.com/labbsr0x/bindman-dns-webhook"
  version = "1.0.0"

[[constraint]]
  name = "github.com/Azure/azure-sdk-for-go"
  version = "31.0.0"

[[constraint]]
  name = "github.com/aliyun/alibaba-cloud-sdk-go"
  version = "1.60.57"

[[constraint]]
  name = "github.com/cloudflare/cloudflare-go"
  version = "0.9.2"

[[constraint]]
  name = "github.com/cpu/goacmedns"
  branch = "master"

[[constraint]]
  name = "github.com/nrdcg/namesilo"
  version = "0.2.0"

[[constraint]]
  name = "github.com/vultr/govultr"
  version = "0.1.4"
