Name = "Hosting.nl"
Description = ''''''
URL = "https://hosting.nl"
Code = "hostingnl"
Since = "v4.30.0"

Example = '''
HOSTINGNL_API_KEY="xxxxxxxxxxxxxxxxxxxxx" \
lego --dns hostingnl -d '*.example.com' -d example.com run
'''

[Configuration]
  [Configuration.Credentials]
    HOSTINGNL_API_KEY = "The API key"
  [Configuration.Additional]
    HOSTINGNL_POLLING_INTERVAL = "Time between DNS propagation check in seconds (Default: 2)"
    HOSTINGNL_PROPAGATION_TIMEOUT = "Maximum waiting time for DNS propagation in seconds (Default: 120)"
    HOSTINGNL_TTL = "The TTL of the TXT record used for the DNS challenge in seconds (Default: 120)"
    HOSTINGNL_HTTP_TIMEOUT = "API request timeout in seconds (Default: 10)"

[Links]
  API = "https://api.hosting.nl/api/documentation"
