Name = "Name.com"
Description = ''''''
URL = "https://www.name.com"
Code = "namedotcom"
Since = "v0.5.0"

Example = '''
NAMECOM_USERNAME=foo.bar \
NAMECOM_API_TOKEN=a379a6f6eeafb9a55e378c118034e2751e682fab \
lego --email you@example.com --dns namedotcom --domains my.example.org run
'''

[Configuration]
  [Configuration.Credentials]
    NAMECOM_USERNAME = "Username"
    NAMECOM_API_TOKEN = "API token"
  [Configuration.Additional]
    NAMECOM_POLLING_INTERVAL = "Time between DNS propagation check"
    NAMECOM_PROPAGATION_TIMEOUT = "Maximum waiting time for DNS propagation"
    NAMECOM_TTL = "The TTL of the TXT record used for the DNS challenge"
    NAMECOM_HTTP_TIMEOUT = "API request timeout"

[Links]
  API = "https://www.name.com/api-docs/DNS"
  GoClient = "https://github.com/namedotcom/go"

