Name = "Curanet"
Description = ''''''
URL = "https://curanet.dk/"
Code = "curanet"
Since = "v4.32.0"

Example = '''
CURANET_API_KEY="xxxxxxxxxxxxxxxxxxxxx" \
lego --dns curanet -d '*.example.com' -d example.com run
'''

[Configuration]
  [Configuration.Credentials]
    CURANET_API_KEY = "API key"
  [Configuration.Additional]
    CURANET_POLLING_INTERVAL = "Time between DNS propagation check in seconds (Default: 2)"
    CURANET_PROPAGATION_TIMEOUT = "Maximum waiting time for DNS propagation in seconds (Default: 60)"
    CURANET_TTL = "The TTL of the TXT record used for the DNS challenge in seconds (Default: 120)"
    CURANET_HTTP_TIMEOUT = "API request timeout in seconds (Default: 30)"

[Links]
  API = "https://api.curanet.dk/dns/swagger/index.html"
