Name = "Efficient IP"
Description = ''''''
URL = "https://efficientip.com/"
Code = "efficientip"
Since = "v4.13.0"

Example = '''
EFFICIENTIP_USERNAME="user" \
EFFICIENTIP_PASSWORD="secret" \
EFFICIENTIP_HOSTNAME="ipam.example.org" \
EFFICIENTIP_DNS_NAME="dns.smart" \
lego --email you@example.com --dns efficientip -d '*.example.com' -d example.com run
'''

[Configuration]
  [Configuration.Credentials]
    EFFICIENTIP_USERNAME = "Username"
    EFFICIENTIP_PASSWORD = "Password"
    EFFICIENTIP_HOSTNAME = "Hostname (ex: foo.example.com)"
    EFFICIENTIP_DNS_NAME = "DNS name (ex: dns.smart)"
  [Configuration.Additional]
    EFFICIENTIP_INSECURE_SKIP_VERIFY = "Whether or not to verify EfficientIP API certificate"
    EFFICIENTIP_VIEW_NAME = "View name (ex: external)"
    EFFICIENTIP_POLLING_INTERVAL = "Time between DNS propagation check"
    EFFICIENTIP_PROPAGATION_TIMEOUT = "Maximum waiting time for DNS propagation"
    EFFICIENTIP_TTL = "The TTL of the TXT record used for the DNS challenge"
    EFFICIENTIP_HTTP_TIMEOUT = "API request timeout"
