Name = "DNSExit"
Description = ''''''
URL = "https://dnsexit.com"
Code = "dnsexit"
Since = "v4.32.0"

Example = '''
DNSEXIT_API_KEY="xxxxxxxxxxxxxxxxxxxxx" \
lego --dns dnsexit -d '*.example.com' -d example.com run
'''

[Configuration]
  [Configuration.Credentials]
    DNSEXIT_API_KEY = "API key"
  [Configuration.Additional]
    DNSEXIT_POLLING_INTERVAL = "Time between DNS propagation check in seconds (Default: 10)"
    DNSEXIT_PROPAGATION_TIMEOUT = "Maximum waiting time for DNS propagation in seconds (Default: 300)"
    DNSEXIT_TTL = "The TTL of the TXT record used for the DNS challenge in seconds (Default: 120)"
    DNSEXIT_HTTP_TIMEOUT = "API request timeout in seconds (Default: 30)"

[Links]
  API = "https://dnsexit.com/dns/dns-api/"
