Name = "all-inkl"
Description = ''''''
URL = "https://all-inkl.com"
Code = "allinkl"
Since = "v4.5.0"

Example = '''
ALL_INKL_LOGIN=xxxxxxxxxxxxxxxxxxxxxxxxxx \
ALL_INKL_PASSWORD=yyyyyyyyyyyyyyyyyyyyyyyyyy \
lego --email you@example.com --dns allinkl --domains my.example.org run
'''

[Configuration]
  [Configuration.Credentials]
    ALL_INKL_LOGIN = "KAS login"
    ALL_INKL_PASSWORD = "KAS password"
  [Configuration.Additional]
    ALL_INKL_POLLING_INTERVAL = "Time between DNS propagation check"
    ALL_INKL_PROPAGATION_TIMEOUT = "Maximum waiting time for DNS propagation"
    ALL_INKL_HTTP_TIMEOUT = "API request timeout"

[Links]
  API = "https://kasapi.kasserver.com/dokumentation/phpdoc/index.html"
  Guide = "https://kasapi.kasserver.com/dokumentation/"
