Name = "ArvanCloud"
Description = ''''''
URL = "https://arvancloud.ir"
Code = "arvancloud"
Since = "v3.8.0"

Example = '''
ARVANCLOUD_API_KEY="Apikey xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx" \
lego --email you@example.com --dns arvancloud -d '*.example.com' -d example.com run
'''

[Configuration]
  [Configuration.Credentials]
    ARVANCLOUD_API_KEY = "API key"
  [Configuration.Additional]
    ARVANCLOUD_POLLING_INTERVAL = "Time between DNS propagation check"
    ARVANCLOUD_PROPAGATION_TIMEOUT = "Maximum waiting time for DNS propagation"
    ARVANCLOUD_TTL = "The TTL of the TXT record used for the DNS challenge"
    ARVANCLOUD_HTTP_TIMEOUT = "API request timeout"

[Links]
  API = "https://www.arvancloud.ir/docs/api/cdn/4.0"
