Name = "Autodns"
Description = ''''''
URL = "https://www.internetx.com/domains/autodns/"
Code = "autodns"
Since = "v3.2.0"

Example = '''
AUTODNS_API_USER=username \
AUTODNS_API_PASSWORD=supersecretpassword \
lego --email you@example.com --dns autodns --domains my.example.org run
'''

[Configuration]
  [Configuration.Credentials]
    AUTODNS_API_USER = "Username"
    AUTODNS_API_PASSWORD = "User Password"
  [Configuration.Additional]
    AUTODNS_ENDPOINT = "API endpoint URL, defaults to https://api.autodns.com/v1/"
    AUTODNS_CONTEXT = "API context (4 for production, 1 for testing. Defaults to 4)"
    AUTODNS_TTL = "The TTL of the TXT record used for the DNS challenge"
    AUTODNS_POLLING_INTERVAL = "Time between DNS propagation check"
    AUTODNS_PROPAGATION_TIMEOUT = "Maximum waiting time for DNS propagation"
    AUTODNS_HTTP_TIMEOUT = "API request timeout, defaults to 30 seconds"

[Links]
  API = "https://help.internetx.com/display/APIJSONEN"
