Name = "DanDomain"
Description = ''''''
URL = "https://dandomain.dk/"
Code = "dandomain"
Since = "v4.32.0"

Example = '''
DANDOMAIN_API_KEY="xxxxxxxxxxxxxxxxxxxxx" \
lego --dns dandomain -d '*.example.com' -d example.com run
'''

[Configuration]
  [Configuration.Credentials]
    DANDOMAIN_API_KEY = "API key"
  [Configuration.Additional]
    DANDOMAIN_POLLING_INTERVAL = "Time between DNS propagation check in seconds (Default: 2)"
    DANDOMAIN_PROPAGATION_TIMEOUT = "Maximum waiting time for DNS propagation in seconds (Default: 60)"
    DANDOMAIN_TTL = "The TTL of the TXT record used for the DNS challenge in seconds (Default: 120)"
    DANDOMAIN_HTTP_TIMEOUT = "API request timeout in seconds (Default: 30)"

[Links]
  API = "https://api.dandomain.dk/dns/swagger/index.html"
