Name = "Simply.com"
Description = ''''''
URL = "https://www.simply.com/en/domains/"
Code = "simply"
Since = "v4.4.0"

Example = '''
SIMPLY_ACCOUNT_NAME=xxxxxx \
SIMPLY_API_KEY=yyyyyy \
lego --email you@example.com --dns simply -d '*.example.com' -d example.com run
'''

[Configuration]
  [Configuration.Credentials]
    SIMPLY_ACCOUNT_NAME = "Account name"
    SIMPLY_API_KEY = "API key"
  [Configuration.Additional]
    SIMPLY_POLLING_INTERVAL = "Time between DNS propagation check"
    SIMPLY_PROPAGATION_TIMEOUT = "Maximum waiting time for DNS propagation"
    SIMPLY_TTL = "The TTL of the TXT record used for the DNS challenge"
    SIMPLY_HTTP_TIMEOUT = "API request timeout"

[Links]
  API = "https://www.simply.com/en/docs/api/"
