Name = "Namecheap"
URL = "https://www.namecheap.com"
Code = "namecheap"
Since = "v0.3.0"
Description = '''

Configuration for [Namecheap](https://www.namecheap.com).

**To enable API access on the Namecheap production environment, some opaque requirements must be met.**
More information in the section [Enabling API Access](https://www.namecheap.com/support/api/intro/) of the Namecheap documentation.
(2020-08: Account balance of $50+, 20+ domains in your account, or purchases totaling $50+ within the last 2 years.)
'''

Example = '''
NAMECHEAP_API_USER=user \
NAMECHEAP_API_KEY=key \
lego --email you@example.com --dns namecheap --domains my.example.org run
'''

[Configuration]
  [Configuration.Credentials]
    NAMECHEAP_API_USER = "API user"
    NAMECHEAP_API_KEY = "API key"
  [Configuration.Additional]
    NAMECHEAP_POLLING_INTERVAL = "Time between DNS propagation check"
    NAMECHEAP_PROPAGATION_TIMEOUT = "Maximum waiting time for DNS propagation"
    NAMECHEAP_TTL = "The TTL of the TXT record used for the DNS challenge"
    NAMECHEAP_HTTP_TIMEOUT = "API request timeout"
    NAMECHEAP_SANDBOX = "Activate the sandbox (boolean)"

[Links]
  API = "https://www.namecheap.com/support/api/methods.aspx"
