Name = "Servercow"
Description = ''''''
URL = "https://servercow.de/"
Code = "servercow"
Since = "v3.4.0"

Example = '''
SERVERCOW_USERNAME=xxxxxxxx \
SERVERCOW_PASSWORD=xxxxxxxx \
lego --dns servercow -d '*.example.com' -d example.com run
'''

[Configuration]
  [Configuration.Credentials]
    SERVERCOW_USERNAME = "API username"
    SERVERCOW_PASSWORD = "API password"
  [Configuration.Additional]
    SERVERCOW_POLLING_INTERVAL = "Time between DNS propagation check in seconds (Default: 2)"
    SERVERCOW_PROPAGATION_TIMEOUT = "Maximum waiting time for DNS propagation in seconds (Default: 60)"
    SERVERCOW_TTL = "The TTL of the TXT record used for the DNS challenge in seconds (Default: 120)"
    SERVERCOW_HTTP_TIMEOUT = "API request timeout in seconds (Default: 30)"

[Links]
  API = "https://wiki.servercow.de/en/domains/dns_api/api-syntax/"
