Name = "Volcano Engine/火山引擎"
Description = ''''''
URL = "https://www.volcengine.com/"
Code = "volcengine"
Since = "v4.19.0"

Example = '''
VOLC_ACCESSKEY=xxx \
VOLC_SECRETKEY=yyy \
lego --email you@example.com --dns volcengine --domains "example.org" --domains "*.example.org" run
'''

[Configuration]
  [Configuration.Credentials]
    VOLC_ACCESSKEY = "Access Key ID (AK)"
    VOLC_SECRETKEY = "Secret Access Key (SK)"
  [Configuration.Additional]
    VOLC_REGION = "Region"
    VOLC_HOST = "API host"
    VOLC_SCHEME = "API scheme"
    VOLC_POLLING_INTERVAL = "Time between DNS propagation check"
    VOLC_PROPAGATION_TIMEOUT = "Maximum waiting time for DNS propagation"
    VOLC_TTL = "The TTL of the TXT record used for the DNS challenge"
    VOLC_HTTP_TIMEOUT = "API request timeout"

[Links]
  API = "https://www.volcengine.com/docs/6758/155086"
  GoClient = "https://github.com/volcengine/volc-sdk-golang"
