Name = "Derak Cloud"
Description = ''''''
URL = "https://derak.cloud/"
Code = "derak"
Since = "v4.12.0"

Example = '''
DERAK_API_KEY="xxxxxxxxxxxxxxxxxxxxx" \
lego --email you@example.com --dns derak -d '*.example.com' -d example.com run
'''

[Configuration]
  [Configuration.Credentials]
    DERAK_API_KEY = "The API key"
  [Configuration.Additional]
    DERAK_WEBSITE_ID = "Force the zone/website ID"
    DERAK_POLLING_INTERVAL = "Time between DNS propagation check"
    DERAK_PROPAGATION_TIMEOUT = "Maximum waiting time for DNS propagation"
    DERAK_TTL = "The TTL of the TXT record used for the DNS challenge"
    DERAK_HTTP_TIMEOUT = "API request timeout"
