Name = "EdgeCenter"
Description = ''''''
URL = "https://edgecenter.ru/dns"
Code = "edgecenter"
Since = "v4.29.0"

Example = '''
EDGECENTER_PERMANENT_API_TOKEN=xxxxx \
lego --dns edgecenter -d '*.example.com' -d example.com run
'''

[Configuration]
  [Configuration.Credentials]
    EDGECENTER_PERMANENT_API_TOKEN = "Permanent API token (https://edgecenter.ru/blog/permanent-api-token-explained/)"
  [Configuration.Additional]
    EDGECENTER_POLLING_INTERVAL = "Time between DNS propagation check in seconds (Default: 20)"
    EDGECENTER_PROPAGATION_TIMEOUT = "Maximum waiting time for DNS propagation in seconds (Default: 360)"
    EDGECENTER_TTL = "The TTL of the TXT record used for the DNS challenge in seconds (Default: 120)"
    EDGECENTER_HTTP_TIMEOUT = "API request timeout in seconds (Default: 10)"

[Links]
  API = "https://apidocs.edgecenter.ru/dns"
