Name = "Selectel v2"
Description = ''''''
URL = "https://selectel.ru"
Code = "selectelv2"
Since = "v4.17.0"

Example = '''
SELECTELV2_USERNAME=trex \
SELECTELV2_PASSWORD=xxxxx \
SELECTELV2_ACCOUNT_ID=1234567 \
SELECTELV2_PROJECT_ID=111a11111aaa11aa1a11aaa11111aa1a \
lego --email you@example.com --dns selectelv2 -d '*.example.com' -d example.com run
'''

[Configuration]
  [Configuration.Credentials]
    SELECTELV2_USERNAME = "Openstack username"
    SELECTELV2_PASSWORD = "Openstack username's password"
    SELECTELV2_ACCOUNT_ID = "Selectel account ID (INT)"
    SELECTELV2_PROJECT_ID = "Cloud project ID (UUID)"
  [Configuration.Additional]
    SELECTELV2_BASE_URL = "API endpoint URL"
    SELECTELV2_POLLING_INTERVAL = "Time between DNS propagation check"
    SELECTELV2_PROPAGATION_TIMEOUT = "Maximum waiting time for DNS propagation"
    SELECTELV2_TTL = "The TTL of the TXT record used for the DNS challenge"
    SELECTELV2_HTTP_TIMEOUT = "API request timeout"

[Links]
  API = "https://developers.selectel.ru/docs/cloud-services/dns_api/dns_api_actual/"
  GoClient = "https://github.com/selectel/domains-go"
