Name = "Variomedia"
Description = ''''''
URL = "https://www.variomedia.de/"
Code = "variomedia"
Since = "v4.8.0"

Example = '''
VARIOMEDIA_API_TOKEN=xxxx \
lego --email you@example.com --dns variomedia --domains my.example.org run
'''

[Configuration]
  [Configuration.Credentials]
    VARIOMEDIA_API_TOKEN = "API token"
  [Configuration.Additional]
    VARIOMEDIA_POLLING_INTERVAL = "Time between DNS propagation check"
    VARIOMEDIA_PROPAGATION_TIMEOUT = "Maximum waiting time for DNS propagation"
    VARIOMEDIA_TTL = "The TTL of the TXT record used for the DNS challenge"
    VARIOMEDIA_SEQUENCE_INTERVAL = "Time between sequential requests"
    VARIOMEDIA_HTTP_TIMEOUT = "API request timeout"

[Links]
  API = "https://api.variomedia.de/docs/dns-records.html"
