Name = "Infomaniak"
Description = ''''''
URL = "https://www.infomaniak.com/"
Code = "infomaniak"
Since = "v4.1.0"

Example = '''
INFOMANIAK_ACCESS_TOKEN=1234567898765432 \
lego --email you@example.com --dns infomaniak --domains my.example.org run
'''

Additional = '''
## Access token

Access token can be created at the url https://manager.infomaniak.com/v3/infomaniak-api.
You will need domain scope.
'''

[Configuration]
  [Configuration.Credentials]
    INFOMANIAK_ACCESS_TOKEN = "Access token"
  [Configuration.Additional]
    INFOMANIAK_ENDPOINT = "https://api.infomaniak.com"
    INFOMANIAK_POLLING_INTERVAL = "Time between DNS propagation check"
    INFOMANIAK_PROPAGATION_TIMEOUT = "Maximum waiting time for DNS propagation"
    INFOMANIAK_TTL = "The TTL of the TXT record used for the DNS challenge in seconds"
    INFOMANIAK_HTTP_TIMEOUT = "API request timeout"

[Links]
  API = "https://api.infomaniak.com/doc"
