Name = "IONOS Cloud"
Description = ''''''
URL = "https://cloud.ionos.de/network/cloud-dns"
Code = "ionoscloud"
Since = "vX.Y.Z"

Example = '''
IONOSCLOUD_TOKEN=xxxxxxxx \
lego --email you@example.com --dns ionoscloud -d '*.example.com' -d example.com run
'''

[Configuration]
  [Configuration.Credentials]
    IONOSCLOUD_TOKEN = "Bearer token for the Public DNS API (see https://api.ionos.com/docs/dns/v1/)"
  [Configuration.Additional]
    IONOSCLOUD_POLLING_INTERVAL = "Time between DNS propagation check in seconds (Default: 2)"
    IONOSCLOUD_PROPAGATION_TIMEOUT = "Maximum waiting time for DNS propagation in seconds (Default: 900)"
    IONOSCLOUD_TTL = "The TTL of the TXT record used for the DNS challenge in seconds (Default: 300)"
    IONOSCLOUD_HTTP_TIMEOUT = "API request timeout in seconds (Default: 30)"

[Links]
  API = "https://api.ionos.com/docs/dns/v1/"
