Name = "INWX"
Description = ''''''
URL = "https://www.inwx.de/en"
Code = "inwx"
Since = "v2.0.0"

Example = '''
INWX_USERNAME=xxxxxxxxxx \
INWX_PASSWORD=yyyyyyyyyy \
lego --email you@example.com --dns inwx -d '*.example.com' -d example.com run

# 2FA
INWX_USERNAME=xxxxxxxxxx \
INWX_PASSWORD=yyyyyyyyyy \
INWX_SHARED_SECRET=zzzzzzzzzz \
lego --email you@example.com --dns inwx -d '*.example.com' -d example.com run
'''

[Configuration]
  [Configuration.Credentials]
    INWX_USERNAME = "Username"
    INWX_PASSWORD = "Password"
  [Configuration.Additional]
    INWX_SHARED_SECRET = "shared secret related to 2FA"
    INWX_POLLING_INTERVAL = "Time between DNS propagation check"
    INWX_PROPAGATION_TIMEOUT = "Maximum waiting time for DNS propagation (default 360s)"
    INWX_TTL = "The TTL of the TXT record used for the DNS challenge"
    INWX_SANDBOX = "Activate the sandbox (boolean)"

[Links]
  API = "https://www.inwx.de/en/help/apidoc"
  GoClient = "https://github.com/nrdcg/goinwx"
