Name = "Tencent EdgeOne"
Description = ''''''
URL = "https://edgeone.ai"
Code = "edgeone"
Since = "v4.26.0"

Example = '''
EDGEONE_SECRET_ID=abcdefghijklmnopqrstuvwx \
EDGEONE_SECRET_KEY=your-secret-key \
lego --dns edgeone -d '*.example.com' -d example.com run
'''

[Configuration]
  [Configuration.Credentials]
    EDGEONE_SECRET_ID = "Access key ID"
    EDGEONE_SECRET_KEY = "Access Key secret"
  [Configuration.Additional]
    EDGEONE_SESSION_TOKEN = "Access Key token"
    EDGEONE_REGION = "Region"
    EDGEONE_ZONES_MAPPING = "Mapping between DNS zones and site IDs. (ex: 'example.org:id1,example.com:id2')"
    EDGEONE_POLLING_INTERVAL = "Time between DNS propagation check in seconds (Default: 30)"
    EDGEONE_PROPAGATION_TIMEOUT = "Maximum waiting time for DNS propagation in seconds (Default: 1200)"
    EDGEONE_TTL = "The TTL of the TXT record used for the DNS challenge in seconds (Default: 60)"
    EDGEONE_HTTP_TIMEOUT = "API request timeout in seconds (Default: 30)"

[Links]
  API = "https://edgeone.ai/document/50454#dns-record-apis"
  GoClient = "https://github.com/tencentcloud/tencentcloud-sdk-go"
