Name = "Versio.[nl|eu|uk]"
Description = ''''''
URL = "https://www.versio.nl/domeinnamen"
Code = "versio"
Since = "v2.7.0"

Example = '''
VERSIO_USERNAME=<your login> \
VERSIO_PASSWORD=<your password> \
lego --email you@example.com --dns versio --domains my.example.org run
'''

Additional = '''
To test with the sandbox environment set ```VERSIO_ENDPOINT=https://www.versio.nl/testapi/v1/```
'''

[Configuration]
  [Configuration.Credentials]
    VERSIO_USERNAME = "Basic authentication username"
    VERSIO_PASSWORD = "Basic authentication password"
  [Configuration.Additional]
    VERSIO_ENDPOINT = "The endpoint URL of the API Server"
    VERSIO_POLLING_INTERVAL = "Time between DNS propagation check"
    VERSIO_PROPAGATION_TIMEOUT = "Maximum waiting time for DNS propagation"
    VERSIO_HTTP_TIMEOUT = "API request timeout"
    VERSIO_SEQUENCE_INTERVAL = "Time between sequential requests, default 60s"
    VERSIO_TTL = "The TTL of the TXT record used for the DNS challenge"

[Links]
  API = "https://www.versio.nl/RESTapidoc/"
