Name = "Exoscale"
Description = ''''''
URL = "https://www.exoscale.com/"
Code = "exoscale"
Since = "v0.4.0"

Example = '''
EXOSCALE_API_KEY=abcdefghijklmnopqrstuvwx \
EXOSCALE_API_SECRET=xxxxxxx \
lego --email you@example.com --dns exoscale --domains my.example.org run
'''

[Configuration]
  [Configuration.Credentials]
    EXOSCALE_API_KEY = "API key"
    EXOSCALE_API_SECRET = "API secret"
  [Configuration.Additional]
    EXOSCALE_ENDPOINT = "API endpoint URL"
    EXOSCALE_POLLING_INTERVAL = "Time between DNS propagation check"
    EXOSCALE_PROPAGATION_TIMEOUT = "Maximum waiting time for DNS propagation"
    EXOSCALE_TTL = "The TTL of the TXT record used for the DNS challenge"
    EXOSCALE_HTTP_TIMEOUT = "API request timeout"

[Links]
  API = "https://openapi-v2.exoscale.com/#endpoint-dns"
  GoClient = "https://github.com/exoscale/egoscale"
