Name = "Njalla"
Description = ''''''
URL = "https://njal.la"
Code = "njalla"
Since = "v4.3.0"

Example = '''
NJALLA_TOKEN=xxxxxxxxxxxxxxxxxxxxxxxxxx \
lego --email you@example.com --dns njalla -d '*.example.com' -d example.com run
'''

[Configuration]
  [Configuration.Credentials]
    NJALLA_TOKEN = "API token"
  [Configuration.Additional]
    NJALLA_POLLING_INTERVAL = "Time between DNS propagation check"
    NJALLA_PROPAGATION_TIMEOUT = "Maximum waiting time for DNS propagation"
    NJALLA_TTL = "The TTL of the TXT record used for the DNS challenge"
    NJALLA_HTTP_TIMEOUT = "API request timeout"

[Links]
  API = "https://njal.la/api/"
