Name = "VegaDNS"
Description = ''''''
URL = "https://github.com/shupp/VegaDNS-API"
Code = "vegadns"
Since = "v1.1.0"

Example = ''''''

[Configuration]
  [Configuration.Credentials]
    SECRET_VEGADNS_KEY = "API key"
    SECRET_VEGADNS_SECRET = "API secret"
    VEGADNS_URL = "API endpoint URL"
  [Configuration.Additional]
    VEGADNS_POLLING_INTERVAL = "Time between DNS propagation check in seconds (Default: 60)"
    VEGADNS_PROPAGATION_TIMEOUT = "Maximum waiting time for DNS propagation in seconds (Default: 720)"
    VEGADNS_TTL = "The TTL of the TXT record used for the DNS challenge in seconds (Default: 10)"

[Links]
  API = "https://github.com/shupp/VegaDNS-API"
  GoClient = "https://github.com/OpenDNS/vegadns2client"

