Name = "Bluecat"
Description = ''''''
URL = "https://www.bluecatnetworks.com"
Code = "bluecat"
Since = "v0.5.0"

Example = '''
BLUECAT_PASSWORD=mypassword \
BLUECAT_DNS_VIEW=myview \
BLUECAT_USER_NAME=myusername \
BLUECAT_CONFIG_NAME=myconfig \
BLUECAT_SERVER_URL=https://bam.example.com \
BLUECAT_TTL=30 \
lego --email you@example.com --dns bluecat -d '*.example.com' -d example.com run
'''

[Configuration]
  [Configuration.Credentials]
    BLUECAT_SERVER_URL = "The server URL, should have scheme, hostname, and port (if required) of the authoritative Bluecat BAM serve"
    BLUECAT_USER_NAME = "API username"
    BLUECAT_PASSWORD = "API password"
    BLUECAT_CONFIG_NAME = "Configuration name"
    BLUECAT_DNS_VIEW = "External DNS View Name"
  [Configuration.Additional]
    BLUECAT_POLLING_INTERVAL = "Time between DNS propagation check"
    BLUECAT_PROPAGATION_TIMEOUT = "Maximum waiting time for DNS propagation"
    BLUECAT_TTL = "The TTL of the TXT record used for the DNS challenge"
    BLUECAT_HTTP_TIMEOUT = "API request timeout"
    BLUECAT_SKIP_DEPLOY = "Skip deployements"

[Links]
  API = "https://docs.bluecatnetworks.com/r/Address-Manager-API-Guide/REST-API/9.1.0"
